#!/usr/bin/env bash
# Installing Nginx to server
apt-get -y update
apt-get install -y nginx
mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index/txt
echo "Hello World!" > /usr/share/nginx/html/index.html
service nginx restart
