#!/usr/bin/env bash
# bash script to configure a custom 404 page
apt-get -y update
apt-get install -y nginx
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

cat <<EOL > /etc/nginx/sites-available/custom_404
server {
    listen 80 default_server;
    server_name 130152-web-01;

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
    }

    location / {
        return 404;
    }
}
EOL
ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/
service nginx reload
