#!/usr/bin/env bash
# Install Nginx
apt-get -y update
apt-get install -y nginx

echo "server {
    listen 80;
    server_name _;

    location / {
        return 404 'Ceci n\'est pas une page';
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
        root /var/www/html;
    }
}" > /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404.html
service nginx restart
