#!/usr/bin/env bash
# install and configure HAproxy on lb-01 server
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install haproxy

sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    maxconn 2000
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 54.157.184.253:80 check
    server web-02 52.87.255.172:80 check
EOF

sudo service haproxy restart

echo "Server names configured: [\"web-01\", \"web-02\"]"
