#!/usr/bin/env bash
# install and configure HAproxy on lb-01 server
sudo apt-get update
sudo apt-get install haproxy

echo "ENABLED=1" >> /etc/default/haproxy

echo -e "\nfrontend localservers\n\tbind *:80\n\tmode http\n\tdefault_backend servers\n\nbackend servers\n\tbalance roundrobin\n\tserver 130152-web-01 54.157.184.253:80 check\n\tserver 130152-web-02 52.87.255.172:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy restart
