#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive

if [ -f backup.sql ]; then
  rm backup.sql
fi

mysqldump -u root -p"$1" --all-databases > backup.sql

tar -czvf `date +%d-%m-%Y`.tar.gz backup.sql
