#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

count=0

while [ $count -lt 10 ]
do
	echo "Best School"
	count=$((count+1))
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
done
