#!/usr/bin/env bash
# displays The content of the current directory in a list format

for file in ./*
do
    if [[ -f "$file" && ! "${file##*-}" = "$file" ]]
    then
        echo "${file##*-}"
    fi
done
