#!/usr/bin/env bash
# script that configures a container

user=nginx
group=nginx

chown -R $user:$group /etc/nginx

chown -R $user:$group /var/log/nginx

chown $user:$group /var/run/nginx.pid

sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/nginx.conf

service nginx restart
